version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: visaflow_db
    environment:
      POSTGRES_DB: visaflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: visaflow_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: visaflow_backend
    command: python manage.py migrate && python manage.py seed_rules && gunicorn visaflow.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    environment:
      - DB_NAME=visaflow_db
      - DB_USER=postgres
      - DB_PASSWORD=secretpassword
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TASK_ALWAYS_EAGER=False
      - DJANGO_DEBUG=False
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: ./backend
    container_name: visaflow_celery
    command: celery -A visaflow worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - DB_NAME=visaflow_db
      - DB_USER=postgres
      - DB_PASSWORD=secretpassword
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TASK_ALWAYS_EAGER=False
    depends_on:
      - redis
      - db

  frontend:
    build: ./frontend
    container_name: visaflow_frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000/api/
    depends_on:
      - backend

volumes:
  postgres_data:
