# Generated by Django 5.2.15 on 2026-06-21 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0002_ai_eligibility_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_score', models.IntegerField(default=0, help_text='Financial strength score based on bank balance and income (0–100)')),
                ('employment_score', models.IntegerField(default=0, help_text='Employment stability score based on letter and salary slip (0–100)')),
                ('travel_history_score', models.IntegerField(default=0, help_text='Travel history score based on countries visited and visa history (0–100)')),
                ('documentation_score', models.IntegerField(default=0, help_text='Documentation quality score based on OCR confidence and completeness (0–100)')),
                ('compliance_score', models.IntegerField(default=0, help_text='Country rule compliance score — pass rate of all country-specific rules (0–100)')),
                ('final_score', models.IntegerField(default=0, help_text='Weighted final eligibility score (0–100). Threshold: 70+ = Eligible')),
                ('weighted_breakdown', models.JSONField(blank=True, default=dict, help_text='Per-category score breakdown with weights and contributions')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='HIGH', help_text='Overall application risk level: LOW, MEDIUM, or HIGH', max_length=10)),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='List of identified risk factors with severity levels')),
                ('cross_validation_results', models.JSONField(blank=True, default=dict, help_text='Cross-document consistency check results')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='Ordered list of AI-generated actionable recommendations')),
                ('strengths', models.JSONField(blank=True, default=list, help_text='List of application strengths identified by the AI engine')),
                ('is_eligible', models.BooleanField(default=False, help_text='AI-determined eligibility (final_score >= 70 and no HIGH risk factors)')),
                ('eligibility_summary', models.TextField(blank=True, default='', help_text='Human-readable AI eligibility summary paragraph')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_score', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'Eligibility Score',
                'verbose_name_plural': 'Eligibility Scores',
                'ordering': ['-created_at'],
            },
        ),
    ]
