# Generated by Django 5.2.15 on 2026-06-21 10:39

import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='AI-powered structured analysis result for this document'),
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('passport', 'Passport'), ('bank_statement', 'Bank Statement'), ('salary_slip', 'Salary Slip'), ('employment_letter', 'Employment Letter'), ('tax_return', 'Tax Return / ITR'), ('travel_history', 'Travel History'), ('invitation_letter', 'Invitation Letter'), ('hotel_booking', 'Hotel Booking'), ('flight_booking', 'Flight Booking / Reservation'), ('cover_letter', 'Cover Letter'), ('other', 'Other')], default='other', help_text='Document category slug used for AI routing', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='OCR extraction confidence score 0.0–1.0'),
        ),
        migrations.AddField(
            model_name='document',
            name='raw_text',
            field=models.TextField(blank=True, default='', help_text='Full raw OCR text extracted from document'),
        ),
        migrations.AddField(
            model_name='submission',
            name='application_id',
            field=models.CharField(default=submissions.models.generate_application_id, help_text='Human-readable application reference ID', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='processing_logs',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of processing events: [{timestamp, event, details}]'),
        ),
        migrations.AddField(
            model_name='submission',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current AI processing pipeline status', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, help_text='MIME type e.g. application/pdf', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(help_text="Display name, e.g. 'Passport'", max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='validation_result',
            field=models.JSONField(blank=True, default=dict, help_text='Rules engine validation details'),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='correct_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='validationreport',
            name='missing_documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
