# Generated by Django 5.2.15 on 2026-06-08 05:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('visa_type', models.CharField(max_length=100)),
                ('required_documents', models.JSONField(help_text="List of document names e.g., ['Passport', 'Bank Statement']")),
                ('rules', models.JSONField(help_text="Key-value pairs for rules, e.g., {'passport_min_validity_months': 6, 'min_bank_balance': 300000}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('country', 'visa_type')},
            },
        ),
    ]
